services:
  image-convert:
    image: image-convert:latest
    container_name: image-convert
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12346:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - EXTERNAL_URL=http://localhost:12346
      - OUTPUT_DIR=/app/outputs
      - SESSION_FILE=/app/data/sessions.json
      - EXPIRATION_TIME=3600 