services:
  image-convert:
    image: image-convert:latest
    container_name: image-convert
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12346:5000"
    volumes:
      - /mnt/fastlane/docker/image-convert/image_uploads:/app/uploads
      - /mnt/fastlane/docker/image-convert/image_outputs:/app/outputs
      - /mnt/fastlane/docker/image-convert/image_data:/app/data
    restart: unless-stopped
    environment:
      - EXTERNAL_URL=https://image-convert.cobaltfilms.be
      - OUTPUT_DIR=/app/outputs
      - SESSION_FILE=/app/data/sessions.json
      - EXPIRATION_TIME=3600 